### ISSUE TITLE
PNG Large

### ISSUE THREAD

**Issue by sudomedo** [freetaxii/stix2-graphics#3]
Hi,

Would you please produce large PNG for all STIX 2.x graphics...

Regards,
MD

**Comment by jordan2175** [comment]
Would 300 dpi version work for you?

**Comment by sudomedo** [comment]
Oh, yeah definitely

**Comment by jordan2175** [comment]
Done

**Comment by sudomedo** [comment]
Looks great, thanks a bunch...
